### ISSUE TITLE
Bash error in `stack build` running executables.

### ISSUE THREAD

**Issue by jasonhemann** [quasarbright/PongChamp#4] opened 2021-03-26 13:16 UTC
When I run `stack build` on my system, I see the following output. I suspect this error is an issue with output data being read as shell commands. 

```
Building all executables for `PongChamp' once. After a successful build of all of them, only specified executables will be rebuilt.
PongChamp> configure (lib + exe)
Configuring PongChamp-0.1.0.0...
PongChamp> build (lib + exe)
Preprocessing library for PongChamp-0.1.0.0..
Building library for PongChamp-0.1.0.0..
[ 1 of 14] Compiling AST
[ 2 of 14] Compiling DynamicTransformer
[ 3 of 14] Compiling GameEngine
[ 4 of 14] Compiling Interpreter
[ 5 of 14] Compiling Learning.Parser2ElectricBoogaloo
[ 6 of 14] Compiling Learning.RecursionSchemes
[ 7 of 14] Compiling Learning.State
[ 8 of 14] Compiling Lib
[ 9 of 14] Compiling ParseUtils
[10 of 14] Compiling Paths_PongChamp
[11 of 14] Compiling Text.Megaparsec.Expr
[12 of 14] Compiling Parser
[13 of 14] Compiling WellFormedness
[14 of 14] Compiling Runner
Preprocessing executable 'PongChamp-exe' for PongChamp-0.1.0.0..
Building executable 'PongChamp-exe' for PongChamp-0.1.0.0..
[1 of 2] Compiling Main
[2 of 2] Compiling Paths_PongChamp
Linking .stack-work/dist/x86_64-osx/Cabal-3.0.1.0/build/PongChamp-exe/PongChamp-exe ...
PongChamp> copy/register
Installing library in /Users/jhemann/Documents/PongChamp/.stack-work/install/x86_64-osx/ea88002000455e9819efb2df7c889d0c7b848ac4029b81166709c04b26779a90/8.8.4/lib/x86_64-osx-ghc-8.8.4/PongChamp-0.1.0.0-49mCpi28uBXC0jLzkaC6qG
Installing executable PongChamp-exe in /Users/jhemann/Documents/PongChamp/.stack-work/install/x86_64-osx/ea88002000455e9819efb2df7c889d0c7b848ac4029b81166709c04b26779a90/8.8.4/bin
Registering library for PongChamp-0.1.0.0..
bash: CNumber: command not found
```

**Comment by RyanRio** [comment] 2021-04-01 03:47
Is this still happening after installing libs? CNumber is indeed an output data type however this is very puzzling.

**Comment by RyanRio** [comment] 2021-04-06 16:13
I believe we found we couldn't reproduce this, so closing for now.

**Closed by RyanRio** 2021-04-06 16:13 UTC
